cwlVersion: v1.2
class: Workflow
label: "Fit Workflow"
doc: >
  This workflow runs Gaussian fit on the data generated by the data-generation workflow.

requirements:
  SubworkflowFeatureRequirement: {}
  MultipleInputFeatureRequirement: {}

inputs:
  data1:
    type: File[]
    default: "data1.txt"
  data2:
    type: File[]
    default: "data2.txt"

outputs:
  fit-data:
    type: File[]
    outputSource:
      - fit-1/fit-data
      - fit-2/fit-data
    linkMerge: merge_flattened
  log:
    type: File[]
    outputSource:
      - fit-1/log
      - fit-2/log
    linkMerge: merge_flattened

steps:
  fit-1:
    run: gaussian-fit.cwl
    in:
      data: data1
    out: [fit-data, log]

  fit-2:
    run: gaussian-fit.cwl
    in:
      data: data2
    out: [fit-data, log]
