id: _:75f8efbb-e5a1-49b7-91d8-fe840bf0aa67
class: Workflow
label: RD_Lb2pKpipiMuMu_Run2_Run3 2016 pp MagUp
doc: |-
  LHCb Production Workflow: RD_Lb2pKpipiMuMu_Run2_Run3 2016 pp MagUp

  Metadata:
    Event Type: 15146001
    MC Config Version: 2016
    Simulation Condition: Beam6500GeV-2016-MagUp-Nu1.6-25ns-Pythia8

  This workflow contains 9 processing steps.

  Generated by ProductionRequestToCWL converter
inputs:
- id: production-id
  doc: Production ID
  default: 12345
  type: int
- id: prod-job-id
  doc: Production Job ID
  default: 6789
  type: int
- id: run-number
  doc: Run number for simulation
  default: 1
  type: int
- id: first-event-number
  doc: First event number in the run
  default: 1
  type: int
- id: number-of-events
  doc: Number of events to generate
  default: 10
  type: int
- id: pool-xml-catalog
  doc: Pool XML catalog file (optional)
  type: File?
- id: histogram
  doc: Enable histogram output
  default: false
  type: boolean
outputs:
- id: output-data-step-9
  label: ALLSTREAMS.DST
  outputSource: Merge_for_ALLSTREAMS_DST/output-data
  type: File[]
- id: others-step-1
  label: Logs and summaries (step 1)
  outputSource: Sim10f_-_2016_-_Beam6500GeV_-_MagUp_-_Pythia8/others
  type: File[]
- id: others-step-2
  label: Logs and summaries (step 2)
  outputSource: Digi15_for_2016_spillover/others
  type: File[]
- id: others-step-3
  label: Logs and summaries (step 3)
  outputSource: L0_emulation_for_2016_-_TCK_0x160F/others
  type: File[]
- id: others-step-4
  label: Logs and summaries (step 4)
  outputSource: TCK-0x5138160F__HLT1__Flagged_for_2016/others
  type: File[]
- id: others-step-5
  label: Logs and summaries (step 5)
  outputSource: TCK-0x6139160F__HLT2__Flagged_for_2016/others
  type: File[]
- id: others-step-6
  label: Logs and summaries (step 6)
  outputSource: Reco16_for_MC_2016/others
  type: File[]
- id: others-step-7
  label: Logs and summaries (step 7)
  outputSource: Turbo_lines__MC__for_2016_Turbo03a/others
  type: File[]
- id: others-step-8
  label: Logs and summaries (step 8)
  outputSource: Stripping28r2p2NoPrescalingFlagged_for_2016/others
  type: File[]
- id: others-step-9
  label: Logs and summaries (step 9)
  outputSource: Merge_for_ALLSTREAMS_DST/others
  type: File[]
- id: pool-xml-catalog-out
  label: Pool XML Catalog
  outputSource: Merge_for_ALLSTREAMS_DST/pool-xml-catalog-out
  type: File
requirements:
- class: MultipleInputFeatureRequirement
- class: StepInputExpressionRequirement
- class: InlineJavascriptRequirement
- class: ResourceRequirement
  coresMin: 1
  coresMax: 1
cwlVersion: v1.2
steps:
- id: Sim10f_-_2016_-_Beam6500GeV_-_MagUp_-_Pythia8
  in:
  - id: output-prefix
    source:
    - production-id
    - prod-job-id
    valueFrom: $(self[0].toString().padStart(8, "0"))_$(self[1].toString().padStart(8, "0"))_1
  - id: run-number
    source: run-number
  - id: first-event-number
    source: first-event-number
  - id: number-of-events
    source: number-of-events
  - id: pool-xml-catalog
    source: pool-xml-catalog
  - id: histogram
    source: histogram
  out:
  - id: output-data
  - id: others
  - id: pool-xml-catalog-out
  run:
    id: _:fa1ae7a3-a29d-4620-aaaa-1e2cfdda23e8
    class: CommandLineTool
    inputs:
    - id: output-prefix
      type: string
      inputBinding:
        prefix: --output-prefix
    - id: run-number
      type: int?
      inputBinding:
        prefix: --run-number
    - id: first-event-number
      type: int?
      inputBinding:
        prefix: --first-event-number
    - id: number-of-events
      type: int
      inputBinding:
        prefix: --number-of-events
    - id: pool-xml-catalog
      type: File?
    - id: histogram
      type: boolean
      inputBinding:
        prefix: --histogram
    outputs:
    - id: output-data
      type: File[]
      outputBinding:
        glob:
        - '*.sim'
    - id: others
      type: File[]
      outputBinding:
        glob:
        - prodConf*.json
        - prodConf*.py
        - summary*.xml
        - prmon*
        - Gauss*.log
    - id: pool-xml-catalog-out
      type: File
      outputBinding:
        glob: pool_xml_catalog.xml
    requirements:
    - class: InitialWorkDirRequirement
      listing:
      - entryname: initialProdConf_1.json
        entry: |-
          {
            "spec_version": 1,
            "application": {
              "name": "Gauss",
              "version": "v56r10p1",
              "data_pkgs": [
                "AppConfig.v3r457",
                "Gen/DecFiles.v32r39"
              ],
              "binary_tag": "x86_64_v2-centos7-gcc11-opt"
            },
            "options": {
              "files": [
                "$APPCONFIGOPTS/Gauss/Beam6500GeV-mu100-2016-nu1.6.py",
                "$APPCONFIGOPTS/Gauss/EnableSpillover-25ns.py",
                "$APPCONFIGOPTS/Gauss/DataType-2016.py",
                "$APPCONFIGOPTS/Gauss/RICHRandomHits.py",
                "$DECFILESROOT/options/15146001.py",
                "$LBPYTHIA8ROOT/options/Pythia8.py",
                "$APPCONFIGOPTS/Gauss/G4PL_FTFP_BERT_EmOpt2.py",
                "$APPCONFIGOPTS/Persistency/BasketSize-10.py",
                "$APPCONFIGOPTS/Persistency/Compression-ZLIB-1.py"
              ],
              "processing_pass": "Sim10f"
            },
            "db_tags": {
              "dddb_tag": "2016-v03.06",
              "conddb_tag": "sim-20201113-6-vc-mu100-Sim10"
            },
            "input": {
              "n_of_events": -1
            },
            "output": {
              "types": [
                "SIM"
              ]
            }
          }
      - entryname: pool_xml_catalog.xml
        entry: $(inputs['pool-xml-catalog'])
    - class: ResourceRequirement
      coresMin: 1
      coresMax: 1
    - class: StepInputExpressionRequirement
    baseCommand:
    - dirac-run-lbprodrun-app
    arguments:
    - initialProdConf_1.json
- id: Digi15_for_2016_spillover
  in:
  - id: output-prefix
    source:
    - production-id
    - prod-job-id
    valueFrom: $(self[0].toString().padStart(8, "0"))_$(self[1].toString().padStart(8, "0"))_2
  - id: run-number
    source: run-number
  - id: number-of-events
    source: number-of-events
  - id: pool-xml-catalog
    source: Sim10f_-_2016_-_Beam6500GeV_-_MagUp_-_Pythia8/pool-xml-catalog-out
  out:
  - id: output-data
  - id: others
  - id: pool-xml-catalog-out
  run:
    id: _:f7eca1e8-bceb-486d-838d-6e4a792e4246
    class: CommandLineTool
    inputs:
    - id: output-prefix
      type: string
      inputBinding:
        prefix: --output-prefix
    - id: run-number
      type: int?
      inputBinding:
        prefix: --run-number
    - id: number-of-events
      type: int
      inputBinding:
        prefix: --number-of-events
    - id: pool-xml-catalog
      type: File
    outputs:
    - id: output-data
      type: File[]
      outputBinding:
        glob:
        - '*.digi'
    - id: others
      type: File[]
      outputBinding:
        glob:
        - prodConf*.json
        - prodConf*.py
        - summary*.xml
        - prmon*
        - Boole*.log
    - id: pool-xml-catalog-out
      type: File
      outputBinding:
        glob: pool_xml_catalog.xml
    requirements:
    - class: InitialWorkDirRequirement
      listing:
      - entryname: initialProdConf_2.json
        entry: |-
          {
            "spec_version": 1,
            "application": {
              "name": "Boole",
              "version": "v33r3",
              "data_pkgs": [
                "AppConfig.v3r457"
              ]
            },
            "options": {
              "files": [
                "$APPCONFIGOPTS/Boole/Default.py",
                "$APPCONFIGOPTS/Boole/EnableSpillover.py",
                "$APPCONFIGOPTS/Boole/DataType-2015.py",
                "$APPCONFIGOPTS/Boole/Boole-SetOdinRndTrigger.py",
                "$APPCONFIGOPTS/Persistency/Compression-ZLIB-1.py"
              ],
              "processing_pass": "Digi15"
            },
            "db_tags": {},
            "input": {
              "n_of_events": -1
            },
            "output": {
              "types": [
                "DIGI"
              ]
            }
          }
      - entryname: pool_xml_catalog.xml
        entry: $(inputs['pool-xml-catalog'])
    - class: ResourceRequirement
      coresMin: 1
      coresMax: 1
    - class: StepInputExpressionRequirement
    baseCommand:
    - dirac-run-lbprodrun-app
    arguments:
    - initialProdConf_2.json
- id: L0_emulation_for_2016_-_TCK_0x160F
  in:
  - id: output-prefix
    source:
    - production-id
    - prod-job-id
    valueFrom: $(self[0].toString().padStart(8, "0"))_$(self[1].toString().padStart(8, "0"))_3
  - id: run-number
    source: run-number
  - id: number-of-events
    source: number-of-events
  - id: pool-xml-catalog
    source: Digi15_for_2016_spillover/pool-xml-catalog-out
  out:
  - id: output-data
  - id: others
  - id: pool-xml-catalog-out
  run:
    id: _:1b6a425c-201e-4ad2-98d1-8970872c3899
    class: CommandLineTool
    inputs:
    - id: output-prefix
      type: string
      inputBinding:
        prefix: --output-prefix
    - id: run-number
      type: int?
      inputBinding:
        prefix: --run-number
    - id: number-of-events
      type: int
      inputBinding:
        prefix: --number-of-events
    - id: pool-xml-catalog
      type: File
    outputs:
    - id: output-data
      type: File[]
      outputBinding:
        glob:
        - '*.digi'
    - id: others
      type: File[]
      outputBinding:
        glob:
        - prodConf*.json
        - prodConf*.py
        - summary*.xml
        - prmon*
        - Moore*.log
    - id: pool-xml-catalog-out
      type: File
      outputBinding:
        glob: pool_xml_catalog.xml
    requirements:
    - class: InitialWorkDirRequirement
      listing:
      - entryname: initialProdConf_3.json
        entry: |-
          {
            "spec_version": 1,
            "application": {
              "name": "Moore",
              "version": "v25r5p3",
              "data_pkgs": [
                "AppConfig.v3r457"
              ]
            },
            "options": {
              "files": [
                "$APPCONFIGOPTS/L0App/L0AppSimProduction.py",
                "$APPCONFIGOPTS/L0App/L0AppTCK-0x160F.py",
                "$APPCONFIGOPTS/L0App/ForceLUTVersionV8.py",
                "$APPCONFIGOPTS/L0App/DataType-2016.py",
                "$APPCONFIGOPTS/Persistency/Compression-ZLIB-1.py"
              ],
              "processing_pass": "L0Trig0x160F",
              "format": "l0app"
            },
            "db_tags": {},
            "input": {
              "n_of_events": -1
            },
            "output": {
              "types": [
                "DIGI"
              ]
            }
          }
      - entryname: pool_xml_catalog.xml
        entry: $(inputs['pool-xml-catalog'])
    - class: ResourceRequirement
      coresMin: 1
      coresMax: 1
    - class: StepInputExpressionRequirement
    baseCommand:
    - dirac-run-lbprodrun-app
    arguments:
    - initialProdConf_3.json
- id: TCK-0x5138160F__HLT1__Flagged_for_2016
  in:
  - id: output-prefix
    source:
    - production-id
    - prod-job-id
    valueFrom: $(self[0].toString().padStart(8, "0"))_$(self[1].toString().padStart(8, "0"))_4
  - id: run-number
    source: run-number
  - id: number-of-events
    source: number-of-events
  - id: pool-xml-catalog
    source: L0_emulation_for_2016_-_TCK_0x160F/pool-xml-catalog-out
  out:
  - id: output-data
  - id: others
  - id: pool-xml-catalog-out
  run:
    id: _:b47589a9-f337-4e3b-a7db-c510b922fd94
    class: CommandLineTool
    inputs:
    - id: output-prefix
      type: string
      inputBinding:
        prefix: --output-prefix
    - id: run-number
      type: int?
      inputBinding:
        prefix: --run-number
    - id: number-of-events
      type: int
      inputBinding:
        prefix: --number-of-events
    - id: pool-xml-catalog
      type: File
    outputs:
    - id: output-data
      type: File[]
      outputBinding:
        glob:
        - '*.digi'
    - id: others
      type: File[]
      outputBinding:
        glob:
        - prodConf*.json
        - prodConf*.py
        - summary*.xml
        - prmon*
        - Moore*.log
    - id: pool-xml-catalog-out
      type: File
      outputBinding:
        glob: pool_xml_catalog.xml
    requirements:
    - class: InitialWorkDirRequirement
      listing:
      - entryname: initialProdConf_4.json
        entry: |-
          {
            "spec_version": 1,
            "application": {
              "name": "Moore",
              "version": "v25r5p3",
              "data_pkgs": [
                "AppConfig.v3r457"
              ]
            },
            "options": {
              "files": [
                "$APPCONFIGOPTS/Moore/MooreSimProductionForSeparateL0AppStep2015.py",
                "$APPCONFIGOPTS/Conditions/TCK-0x5138160F.py",
                "$APPCONFIGOPTS/Moore/DataType-2016.py",
                "$APPCONFIGOPTS/Moore/MooreSimProductionHlt1.py",
                "$APPCONFIGOPTS/Persistency/Compression-ZLIB-1.py"
              ],
              "processing_pass": "Trig0x5138160F"
            },
            "db_tags": {},
            "input": {
              "n_of_events": -1
            },
            "output": {
              "types": [
                "DIGI"
              ]
            }
          }
      - entryname: pool_xml_catalog.xml
        entry: $(inputs['pool-xml-catalog'])
    - class: ResourceRequirement
      coresMin: 1
      coresMax: 1
    - class: StepInputExpressionRequirement
    baseCommand:
    - dirac-run-lbprodrun-app
    arguments:
    - initialProdConf_4.json
- id: TCK-0x6139160F__HLT2__Flagged_for_2016
  in:
  - id: output-prefix
    source:
    - production-id
    - prod-job-id
    valueFrom: $(self[0].toString().padStart(8, "0"))_$(self[1].toString().padStart(8, "0"))_5
  - id: run-number
    source: run-number
  - id: number-of-events
    source: number-of-events
  - id: pool-xml-catalog
    source: TCK-0x5138160F__HLT1__Flagged_for_2016/pool-xml-catalog-out
  out:
  - id: output-data
  - id: others
  - id: pool-xml-catalog-out
  run:
    id: _:f3991aa6-633b-4028-98dc-2d06ae27192d
    class: CommandLineTool
    inputs:
    - id: output-prefix
      type: string
      inputBinding:
        prefix: --output-prefix
    - id: run-number
      type: int?
      inputBinding:
        prefix: --run-number
    - id: number-of-events
      type: int
      inputBinding:
        prefix: --number-of-events
    - id: pool-xml-catalog
      type: File
    outputs:
    - id: output-data
      type: File[]
      outputBinding:
        glob:
        - '*.digi'
    - id: others
      type: File[]
      outputBinding:
        glob:
        - prodConf*.json
        - prodConf*.py
        - summary*.xml
        - prmon*
        - Moore*.log
    - id: pool-xml-catalog-out
      type: File
      outputBinding:
        glob: pool_xml_catalog.xml
    requirements:
    - class: InitialWorkDirRequirement
      listing:
      - entryname: initialProdConf_5.json
        entry: |-
          {
            "spec_version": 1,
            "application": {
              "name": "Moore",
              "version": "v25r5p3",
              "data_pkgs": [
                "AppConfig.v3r457"
              ]
            },
            "options": {
              "files": [
                "$APPCONFIGOPTS/Moore/MooreSimProductionForSeparateL0AppStep2015.py",
                "$APPCONFIGOPTS/Conditions/TCK-0x6139160F.py",
                "$APPCONFIGOPTS/Moore/DataType-2016.py",
                "$APPCONFIGOPTS/Moore/MooreSimProductionHlt2.py",
                "$APPCONFIGOPTS/Persistency/Compression-ZLIB-1.py"
              ],
              "processing_pass": "Trig0x6139160F"
            },
            "db_tags": {},
            "input": {
              "n_of_events": -1
            },
            "output": {
              "types": [
                "DIGI"
              ]
            }
          }
      - entryname: pool_xml_catalog.xml
        entry: $(inputs['pool-xml-catalog'])
    - class: ResourceRequirement
      coresMin: 1
      coresMax: 1
    - class: StepInputExpressionRequirement
    baseCommand:
    - dirac-run-lbprodrun-app
    arguments:
    - initialProdConf_5.json
- id: Reco16_for_MC_2016
  in:
  - id: output-prefix
    source:
    - production-id
    - prod-job-id
    valueFrom: $(self[0].toString().padStart(8, "0"))_$(self[1].toString().padStart(8, "0"))_6
  - id: run-number
    source: run-number
  - id: number-of-events
    source: number-of-events
  - id: pool-xml-catalog
    source: TCK-0x6139160F__HLT2__Flagged_for_2016/pool-xml-catalog-out
  out:
  - id: output-data
  - id: others
  - id: pool-xml-catalog-out
  run:
    id: _:d98039ea-c015-40ab-8cbf-da562f996862
    class: CommandLineTool
    inputs:
    - id: output-prefix
      type: string
      inputBinding:
        prefix: --output-prefix
    - id: run-number
      type: int?
      inputBinding:
        prefix: --run-number
    - id: number-of-events
      type: int
      inputBinding:
        prefix: --number-of-events
    - id: pool-xml-catalog
      type: File
    outputs:
    - id: output-data
      type: File[]
      outputBinding:
        glob:
        - '*.dst'
    - id: others
      type: File[]
      outputBinding:
        glob:
        - prodConf*.json
        - prodConf*.py
        - summary*.xml
        - prmon*
        - Brunel*.log
    - id: pool-xml-catalog-out
      type: File
      outputBinding:
        glob: pool_xml_catalog.xml
    requirements:
    - class: InitialWorkDirRequirement
      listing:
      - entryname: initialProdConf_6.json
        entry: |-
          {
            "spec_version": 1,
            "application": {
              "name": "Brunel",
              "version": "v50r7",
              "data_pkgs": [
                "AppConfig.v3r457"
              ]
            },
            "options": {
              "files": [
                "$APPCONFIGOPTS/Brunel/DataType-2016.py",
                "$APPCONFIGOPTS/Brunel/MC-WithTruth.py",
                "$APPCONFIGOPTS/Brunel/SplitRawEventOutput.4.3.py",
                "$APPCONFIGOPTS/Persistency/Compression-ZLIB-1.py"
              ],
              "processing_pass": "Reco16"
            },
            "db_tags": {},
            "input": {
              "n_of_events": -1
            },
            "output": {
              "types": [
                "DST"
              ]
            }
          }
      - entryname: pool_xml_catalog.xml
        entry: $(inputs['pool-xml-catalog'])
    - class: ResourceRequirement
      coresMin: 1
      coresMax: 1
    - class: StepInputExpressionRequirement
    baseCommand:
    - dirac-run-lbprodrun-app
    arguments:
    - initialProdConf_6.json
- id: Turbo_lines__MC__for_2016_Turbo03a
  in:
  - id: output-prefix
    source:
    - production-id
    - prod-job-id
    valueFrom: $(self[0].toString().padStart(8, "0"))_$(self[1].toString().padStart(8, "0"))_7
  - id: run-number
    source: run-number
  - id: number-of-events
    source: number-of-events
  - id: pool-xml-catalog
    source: Reco16_for_MC_2016/pool-xml-catalog-out
  out:
  - id: output-data
  - id: others
  - id: pool-xml-catalog-out
  run:
    id: _:572405f8-84af-48f5-a05c-e037021604c6
    class: CommandLineTool
    inputs:
    - id: output-prefix
      type: string
      inputBinding:
        prefix: --output-prefix
    - id: run-number
      type: int?
      inputBinding:
        prefix: --run-number
    - id: number-of-events
      type: int
      inputBinding:
        prefix: --number-of-events
    - id: pool-xml-catalog
      type: File
    outputs:
    - id: output-data
      type: File[]
      outputBinding:
        glob:
        - '*.dst'
    - id: others
      type: File[]
      outputBinding:
        glob:
        - prodConf*.json
        - prodConf*.py
        - summary*.xml
        - prmon*
        - DaVinci*.log
    - id: pool-xml-catalog-out
      type: File
      outputBinding:
        glob: pool_xml_catalog.xml
    requirements:
    - class: InitialWorkDirRequirement
      listing:
      - entryname: initialProdConf_7.json
        entry: |-
          {
            "spec_version": 1,
            "application": {
              "name": "DaVinci",
              "version": "v41r5",
              "data_pkgs": [
                "AppConfig.v3r457",
                "TurboStreamProd.v4r2p9"
              ]
            },
            "options": {
              "files": [
                "$APPCONFIGOPTS/Turbo/Tesla_2016_LinesFromStreams_MC.py",
                "$APPCONFIGOPTS/Turbo/Tesla_PR_Truth_2016.py",
                "$APPCONFIGOPTS/Turbo/Tesla_Simulation_2016.py",
                "$APPCONFIGOPTS/Persistency/Compression-ZLIB-1.py"
              ],
              "processing_pass": "Turbo03a",
              "format": "Tesla"
            },
            "db_tags": {},
            "input": {
              "n_of_events": -1
            },
            "output": {
              "types": [
                "DST"
              ]
            }
          }
      - entryname: pool_xml_catalog.xml
        entry: $(inputs['pool-xml-catalog'])
    - class: ResourceRequirement
      coresMin: 1
      coresMax: 1
    - class: StepInputExpressionRequirement
    baseCommand:
    - dirac-run-lbprodrun-app
    arguments:
    - initialProdConf_7.json
- id: Stripping28r2p2NoPrescalingFlagged_for_2016
  in:
  - id: output-prefix
    source:
    - production-id
    - prod-job-id
    valueFrom: $(self[0].toString().padStart(8, "0"))_$(self[1].toString().padStart(8, "0"))_8
  - id: run-number
    source: run-number
  - id: number-of-events
    source: number-of-events
  - id: pool-xml-catalog
    source: Turbo_lines__MC__for_2016_Turbo03a/pool-xml-catalog-out
  out:
  - id: output-data
  - id: others
  - id: pool-xml-catalog-out
  run:
    id: _:0428e9e0-5b02-4a7d-a0a2-78292f85b653
    class: CommandLineTool
    inputs:
    - id: output-prefix
      type: string
      inputBinding:
        prefix: --output-prefix
    - id: run-number
      type: int?
      inputBinding:
        prefix: --run-number
    - id: number-of-events
      type: int
      inputBinding:
        prefix: --number-of-events
    - id: pool-xml-catalog
      type: File
    outputs:
    - id: output-data
      type: File[]
      outputBinding:
        glob:
        - '*.allstreams.dst'
    - id: others
      type: File[]
      outputBinding:
        glob:
        - prodConf*.json
        - prodConf*.py
        - summary*.xml
        - prmon*
        - DaVinci*.log
    - id: pool-xml-catalog-out
      type: File
      outputBinding:
        glob: pool_xml_catalog.xml
    requirements:
    - class: InitialWorkDirRequirement
      listing:
      - entryname: initialProdConf_8.json
        entry: |-
          {
            "spec_version": 1,
            "application": {
              "name": "DaVinci",
              "version": "v44r11p6",
              "data_pkgs": [
                "AppConfig.v3r457",
                "TMVAWeights.v1r18"
              ]
            },
            "options": {
              "files": [
                "$APPCONFIGOPTS/DaVinci/DV-Stripping28r2p2-Stripping-MC-NoPrescaling-DST.py",
                "$APPCONFIGOPTS/DaVinci/DV-RedoCaloPID-Stripping_28_24.py",
                "$APPCONFIGOPTS/DaVinci/DataType-2016.py",
                "$APPCONFIGOPTS/DaVinci/InputType-DST.py",
                "$APPCONFIGOPTS/DaVinci/DV-RawEventJuggler-4_3-to-4_3.py",
                "$APPCONFIGOPTS/Persistency/Compression-ZLIB-1.py"
              ],
              "processing_pass": "Stripping28r2p2NoPrescalingFlagged"
            },
            "db_tags": {},
            "input": {
              "n_of_events": -1
            },
            "output": {
              "types": [
                "ALLSTREAMS.DST"
              ]
            }
          }
      - entryname: pool_xml_catalog.xml
        entry: $(inputs['pool-xml-catalog'])
    - class: ResourceRequirement
      coresMin: 1
      coresMax: 1
    - class: StepInputExpressionRequirement
    baseCommand:
    - dirac-run-lbprodrun-app
    arguments:
    - initialProdConf_8.json
- id: Merge_for_ALLSTREAMS_DST
  in:
  - id: output-prefix
    source:
    - production-id
    - prod-job-id
    valueFrom: $(self[0].toString().padStart(8, "0"))_$(self[1].toString().padStart(8, "0"))_9
  - id: run-number
    source: run-number
  - id: number-of-events
    source: number-of-events
  - id: pool-xml-catalog
    source: Stripping28r2p2NoPrescalingFlagged_for_2016/pool-xml-catalog-out
  out:
  - id: output-data
  - id: others
  - id: pool-xml-catalog-out
  run:
    id: _:3c8e5351-79b8-4c69-84f1-61fc1c5da945
    class: CommandLineTool
    inputs:
    - id: output-prefix
      type: string
      inputBinding:
        prefix: --output-prefix
    - id: run-number
      type: int?
      inputBinding:
        prefix: --run-number
    - id: number-of-events
      type: int
      inputBinding:
        prefix: --number-of-events
    - id: pool-xml-catalog
      type: File
    outputs:
    - id: output-data
      type: File[]
      outputBinding:
        glob:
        - '*.allstreams.dst'
    - id: others
      type: File[]
      outputBinding:
        glob:
        - prodConf*.json
        - prodConf*.py
        - summary*.xml
        - prmon*
        - DaVinci*.log
    - id: pool-xml-catalog-out
      type: File
      outputBinding:
        glob: pool_xml_catalog.xml
    requirements:
    - class: InitialWorkDirRequirement
      listing:
      - entryname: initialProdConf_9.json
        entry: |-
          {
            "spec_version": 1,
            "application": {
              "name": "DaVinci",
              "version": "v46r17",
              "data_pkgs": [
                "AppConfig.v3r457"
              ]
            },
            "options": {
              "files": [
                "$APPCONFIGOPTS/Merging/DVMergeDST.py",
                "$APPCONFIGOPTS/DaVinci/DataType-2016.py",
                "$APPCONFIGOPTS/Merging/WriteFSR.py",
                "$APPCONFIGOPTS/Merging/MergeFSR.py",
                "$APPCONFIGOPTS/DaVinci/Simulation.py",
                "$APPCONFIGOPTS/Persistency/Compression-LZMA-4.py"
              ],
              "processing_pass": "merging",
              "format": "merge"
            },
            "db_tags": {},
            "input": {
              "n_of_events": -1
            },
            "output": {
              "types": [
                "ALLSTREAMS.DST"
              ]
            }
          }
      - entryname: pool_xml_catalog.xml
        entry: $(inputs['pool-xml-catalog'])
    - class: ResourceRequirement
      coresMin: 1
      coresMax: 1
    - class: StepInputExpressionRequirement
    baseCommand:
    - dirac-run-lbprodrun-app
    arguments:
    - initialProdConf_9.json
