name: Basic Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


defaults:
  run:
    shell: bash -el {0}

jobs:
  pytest:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=3.12
            mypy
            pip
          init-shell: bash
          post-cleanup: 'all'
      - name: Set up environment
        run: |
          pip install .
      - name: Run mypy
        run: |
          mypy src
      - name: Run pytest
        run: |
          pip install .[testing]
          pytest
